# Generated by Django 6.0.1 on 2026-02-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_alter_course_owner_module_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
    ]
